version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - GOLDAPI_KEY=${GOLDAPI_KEY}
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped

networks:
  default:
    driver: bridge
